// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/analytics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{0}
}

type LogPlaybackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       int32                  `protobuf:"varint,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	AmountPaid    float64                `protobuf:"fixed64,2,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogPlaybackRequest) Reset() {
	*x = LogPlaybackRequest{}
	mi := &file_proto_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogPlaybackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogPlaybackRequest) ProtoMessage() {}

func (x *LogPlaybackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogPlaybackRequest.ProtoReflect.Descriptor instead.
func (*LogPlaybackRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *LogPlaybackRequest) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *LogPlaybackRequest) GetAmountPaid() float64 {
	if x != nil {
		return x.AmountPaid
	}
	return 0
}

type TopTrack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopTrack) Reset() {
	*x = TopTrack{}
	mi := &file_proto_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopTrack) ProtoMessage() {}

func (x *TopTrack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopTrack.ProtoReflect.Descriptor instead.
func (*TopTrack) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *TopTrack) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TopTrack) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TopTracksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*TopTrack            `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopTracksResponse) Reset() {
	*x = TopTracksResponse{}
	mi := &file_proto_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopTracksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopTracksResponse) ProtoMessage() {}

func (x *TopTracksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopTracksResponse.ProtoReflect.Descriptor instead.
func (*TopTracksResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *TopTracksResponse) GetTracks() []*TopTrack {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type UpdatePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       int32                  `protobuf:"varint,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	NewPrice      float64                `protobuf:"fixed64,2,opt,name=new_price,json=newPrice,proto3" json:"new_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePriceRequest) Reset() {
	*x = UpdatePriceRequest{}
	mi := &file_proto_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePriceRequest) ProtoMessage() {}

func (x *UpdatePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePriceRequest.ProtoReflect.Descriptor instead.
func (*UpdatePriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePriceRequest) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *UpdatePriceRequest) GetNewPrice() float64 {
	if x != nil {
		return x.NewPrice
	}
	return 0
}

var File_proto_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_proto_rawDesc = "" +
	"\n" +
	"\x15proto/analytics.proto\x12\tanalytics\"\a\n" +
	"\x05Empty\"P\n" +
	"\x12LogPlaybackRequest\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\x05R\atrackId\x12\x1f\n" +
	"\vamount_paid\x18\x02 \x01(\x01R\n" +
	"amountPaid\"6\n" +
	"\bTopTrack\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"@\n" +
	"\x11TopTracksResponse\x12+\n" +
	"\x06tracks\x18\x01 \x03(\v2\x13.analytics.TopTrackR\x06tracks\"L\n" +
	"\x12UpdatePriceRequest\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\x05R\atrackId\x12\x1b\n" +
	"\tnew_price\x18\x02 \x01(\x01R\bnewPrice2\xd2\x01\n" +
	"\x10AnalyticsService\x12>\n" +
	"\vLogPlayback\x12\x1d.analytics.LogPlaybackRequest\x1a\x10.analytics.Empty\x12>\n" +
	"\fGetTopTracks\x12\x10.analytics.Empty\x1a\x1c.analytics.TopTracksResponse\x12>\n" +
	"\vUpdatePrice\x12\x1d.analytics.UpdatePriceRequest\x1a\x10.analytics.EmptyB\x18Z\x16jukebox/analytic/protob\x06proto3"

var (
	file_proto_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_proto_rawDescData []byte
)

func file_proto_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_proto_rawDescData
}

var file_proto_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_analytics_proto_goTypes = []any{
	(*Empty)(nil),              // 0: analytics.Empty
	(*LogPlaybackRequest)(nil), // 1: analytics.LogPlaybackRequest
	(*TopTrack)(nil),           // 2: analytics.TopTrack
	(*TopTracksResponse)(nil),  // 3: analytics.TopTracksResponse
	(*UpdatePriceRequest)(nil), // 4: analytics.UpdatePriceRequest
}
var file_proto_analytics_proto_depIdxs = []int32{
	2, // 0: analytics.TopTracksResponse.tracks:type_name -> analytics.TopTrack
	1, // 1: analytics.AnalyticsService.LogPlayback:input_type -> analytics.LogPlaybackRequest
	0, // 2: analytics.AnalyticsService.GetTopTracks:input_type -> analytics.Empty
	4, // 3: analytics.AnalyticsService.UpdatePrice:input_type -> analytics.UpdatePriceRequest
	0, // 4: analytics.AnalyticsService.LogPlayback:output_type -> analytics.Empty
	3, // 5: analytics.AnalyticsService.GetTopTracks:output_type -> analytics.TopTracksResponse
	0, // 6: analytics.AnalyticsService.UpdatePrice:output_type -> analytics.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_analytics_proto_init() }
func file_proto_analytics_proto_init() {
	if File_proto_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_proto = out.File
	file_proto_analytics_proto_goTypes = nil
	file_proto_analytics_proto_depIdxs = nil
}
